### ISSUE TITLE
Game wont start in the browser locally (Android)

### ISSUE THREAD

**Issue by lexterror** [Pomax/mj#190]
Hi this game wont start in any android browser locally. Do I need a webserver?

**Comment by Pomax** [comment]
If you can't make the code run, that's a good sign you should not be playing around with this code it's not an open source project, it's merely publicly hosted, with a very strict license on what you can do.

If the run instructions are insufficient, you're almost certainly trying to do something that either already has, or is about to, violate the license, and I'd respectively ask you to delete your files again.
