### ISSUE TITLE
penalize players for an illegal win

### ISSUE THREAD

**Issue by Pomax** [Pomax/mj#41]
when players claim a win, the code should post-claim check to see if the hand actually constitutes a winning hand. If not, that player should be penalized and the hand should start over.

**Comment by Arty-chan** [comment]
For example:

```
using random seed 540998955 prng.js:17:3

Starting hand 1. config.js:196:59
hand 1, play 1 config.js:196:59
hand 1, play 2 config.js:196:59
hand 1, play 3 config.js:196:59
hand 1, play 4 config.js:196:59
hand 1, play 5 config.js:196:59
hand 1, play 6 config.js:196:59
hand 1, play 7 config.js:196:59
hand 1, play 8 config.js:196:59
hand 1, play 9 config.js:196:59
hand 1, play 10 config.js:196:59
hand 1, play 11 config.js:196:59
hand 1, play 12 config.js:196:59
hand 1, play 13 config.js:196:59
hand 1, play 14 config.js:196:59
hand 1, play 15 config.js:196:59
Player 0 wins round 1! (hand took 85933ms) config.js:196:59
TypeError: scores[winningplayer] is undefined[Learn More]
```

**Comment by Pomax** [comment]
Actually, this should simply be ruled out as possibility: the code should only show those combinations that actually permit a win. If a player can form a chow or a pung, but only one of those yields a win, it should not offer both choices.

**Comment by Pomax** [comment]
Fixes: the client UI now checks which type of thing the tile can be used to win with, so that choices that woul be legal _play_, but not legal _wins_, are left out.

For example, this is a win claim on bamboo 6. Even though we can _form_ a {4,5,6} chow, that would not let us win, and only the {6,6} pair is offered as win choice:
![image](https://user-images.githubusercontent.com/177243/53070545-5ce7a580-3494-11e9-9b90-93af22b12238.png)
