### ISSUE TITLE
Give player choice to kong

### ISSUE THREAD

**Issue by Arty-chan** [Pomax/mj#44]
Not sure if this is actually an issue.

Game automatically kong'ed bamboo 2s for me, but I might want the 4th one for a chow or some such; though in this case, the 4th bamboo 3 is already discarded so maybe it detects that?

`using random seed 78848214 prng.js:17:3`

![image](https://user-images.githubusercontent.com/1790326/52993429-01041a80-33c9-11e9-972a-b0341166b6d3.png)

**Comment by Pomax** [comment]
https://github.com/Pomax/mj/commit/351cb066a0962ccc81a8f3c2c78c07a3ddbc694c should have added this option, although it might be too intrusive (I'm pretty sure right now it'll ask you whether to kong or not every turn you have an undeclared kong in hand. That probably needs a better UI)

**Comment by Arty-chan** [comment]
I believe this is fixed
