### ISSUE TITLE
Minor: chow tiles display out of order

### ISSUE THREAD

**Issue by Arty-chan** [Pomax/mj#50]
notice players have chows but they show in descending order

![image](https://user-images.githubusercontent.com/1790326/53058179-02842000-3467-11e9-8ce8-1dcd0c78024c.png)

using random seed 1453421967, hand 3

**Comment by Pomax** [comment]
In fact, they're not even ordered descending, they're literally not sorted.

**Comment by Pomax** [comment]
Possibly a bug in `tilebank_sort_function` in `client-ui.js`

**Comment by Pomax** [comment]
fixed. Locked sets started enumeration at 0 instead of 1, so the `if (locknum)` code wouldn't fire correctly on the first locked set (0 is consider false). After fixing that, the comparator did not effect sorting within locked sets either due to it being:
```
    // 2: locked tiles
    if (la || lb) {
      if (la && lb) return la - lb;
      if (la) return -1;
      return 1;
    }
```
rather than the now fixed:
```
    // 2: locked tiles
    if (la || lb) {
      if (la && lb) return (la===lb) ? a - b : la - lb;
      if (la) return -1;
      return 1;
    }
```
