### ISSUE TITLE
Solitaire: tiles don't unselect after bad match

### ISSUE THREAD

**Issue by Arty-chan** [Pomax/mj#6]
**Is this actually a feature request?**
Bugs are for reporting things that don't work, rather than things that work but feel clunky or don't work as well as they should. If things _technically_ work, but you think they can be improved, please go back and pick "feature request" instead. Bugs are purely for when something's genuinely broken.

**Describe the bug**
After bad match, tiles are still selected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select a tile.
2. Select a tile that doesn't match.
3. Select a third tile.
4. See error.

**Expected behaviour**
Tiles get unselected after a bad match, and you select another tile.

**Screenshots**

![image](https://github.com/user-attachments/assets/0757e3dc-5907-452e-934b-9cb80a00b4b2)

**Additional information**
🤷

**Comment by Pomax** [comment]
Thank you for letting me know, I've updated the code and this _should_ be fixed now, but let me know if it isn't.
