### ISSUE TITLE
touch events don't seem to register on tiles

### ISSUE THREAD

**Issue by catherine-leung** [Pomax/mj#88]
having some touch sensing problems using safari on ios.  doesn't seem to be able to click on tiles.  the buttons were fine but when I try to throw out a tile by touching it, it didn't work.

**Comment by Pomax** [comment]
I wonder if this is related to https://github.com/Pomax/mj/issues/86

**Comment by Pomax** [comment]
oooooooh I bet I know why. I added in a mouse button check so that long-press wouldn't kick in for right mouse clicks (e.g. for doing "inspect element" on desktop) but I wrote this:
```
    let listenForLongPress = e => {
      // declaration using mouse = long press
      if (e.which !== 1) return;
      setTimeout(() => {
        if (!listenForInput) return;
        e.stopPropagation();
        e.target.removeEventListener("click", pickAsDiscard);
        this.spawnDeclarationModal(this.getLatestTile(), pickAsDiscard);
      }, 1000);
    };
```
so if an event, say, a touch event, doesn't even _have_ a `which`... well then we just immediately return

**Comment by Pomax** [comment]
changed code to:
```
    let listenForLongPress = e => {
      if (e.type === 'mousedown' && e.which !== 1) return;
      setTimeout(() => {
        if (!listenForInput) return;
        e.stopPropagation();
        e.target.removeEventListener("click", pickAsDiscard);
        this.spawnDeclarationModal(this.getLatestTile(), pickAsDiscard, () => {
          e.target.addEventListener("click", pickAsDiscard);
        });
      }, 1000);
    };
```
So... I think that should work now. Tested using ipad simulation but let me know if things work again!

**Comment by catherine-leung** [comment]
doesn't seem to work for me still.  Using iphone 6s. safari, portrait mode (not sure if any of this makes a different)

**Comment by catherine-leung** [comment]
Doesn't work on my ipad either.

**Comment by Pomax** [comment]
hm, does this work? https://jsbin.com/dosofawoxo/3/edit?output (tap the buttons to change their colour). If neither of those work, then safari isn't firing `click` events on spans. If only the first doesn't work, safari apparently needs tabindex in order to monitor clicks. If both work, then there is some kind of deep mystery going on O_o

**Comment by catherine-leung** [comment]
both work.

**Comment by Pomax** [comment]
aw man, I hate deep magic =(

**Comment by Pomax** [comment]
Alright, new test, both spans should act as clickable buttons, and both spans should support a long-press for spawning a confirm dialog. Can you try to regular click both, then see if they both support long-press, and then after dismissing check if clicking still works?

https://jsbin.com/rarowariza/1/edit?output

Code in case the jsbin disappears:
```
<html>

<style>
span {
  display: inline-block;
  background: white;
  padding:2em;
  border: 1px solid black;
  border-radius: 5px;
  cursor: pointer;
  user-select: none;
  -moz-user-select: none;
  -webkit-user-select: none;
  
}

span.green {
  background: green;
}
</style>

<span>TEST 1</span>
<span tabindex="0">TEST 2</span>

<script>
let listenerActive = false;

let stopListenForLongPress = evt => {
  listenerActive = false;
}

let listenForLongPress = evt => {
  if (evt.type === 'mousedown' && evt.which !== 1) return;
  listenerActive = true;
  setTimeout(() => {
    if (!listenerActive) return;
    evt.stopPropagation();
    evt.target.removeEventListener("click", toggle);
    confirm("can you see this?");
    evt.target.addEventListener("click", toggle);
  }, 1000);
};

let toggle = evt => {
  evt.target.classList.toggle('green');  
}

document
  .querySelector('span:not([tabindex])')
  .addEventListener("click", toggle);


document
  .querySelector('span[tabindex]')
  .addEventListener("click", toggle);

document
  .querySelectorAll('span')
  .forEach(e => {
    e.addEventListener('mousedown', listenForLongPress);
    e.addEventListener('touchstart', listenForLongPress);

    e.addEventListener('mouseup', stopListenForLongPress);
    e.addEventListener('touchend', stopListenForLongPress);
  });
</script>

</html>
```

**Comment by Pomax** [comment]
tested with @artychan's iphone and apparently safari is just bizarre. Both those tests work, but the game page doesn't.

**Comment by Pomax** [comment]
on the upside it's completely broken in Safari on macos too, so I guess I'm debugging on that now.

**Comment by Pomax** [comment]
Found it, and it is _amazing_. The code had `document.querySelector('div:not([data-val]')` in several places and that works in Firefox and Chrome just fine, just not in Safari.

What's wrong with that? Nothing much, other than that _it's not a syntactically correct query selector at all_ because it's missing the closing parens at the end of that `not()` rule. So bizarrely, Safari seems to be doing the right thing, and Firefox and Chrome are not.
